plugins:
  - rubocop-yard

YARD:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'solace.gemspec'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*_test.rb'
    - 'test/usecases/**/*.rb'

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'
    - 'test/usecases/**/*.rb'
    - 'test/factories/**/*.rb'

Naming/AccessorMethodName:
  Enabled: false
