# frozen_string_literal: true

source 'https://rubygems.org'

# Test
gem 'factory_bot'
gem 'minitest', '~> 5.0'
gem 'minitest-hooks'
gem 'rake'

# Local gem
gem 'solace', path: '.'

group :development do
  # TTY Spinner
  gem 'tty-spinner'

  # Yard
  gem 'redcarpet', require: false
  gem 'yard', require: false
  gem 'yardstick', require: false

  # Rubocop
  gem 'rubocop', require: false
  gem 'rubocop-yard', require: false
end
