# frozen_string_literal: true

# Rakefile for running all Minitest tests in the test/ directory
require 'bundler/gem_tasks' # provides build / install / release (used by the release workflow)
require 'rake'
require 'rake/testtask'
require 'fileutils'

PLATFORMS = {
  linux: {
    target: 'x86_64-unknown-linux-gnu',
    ext: 'so',
    rustlib: 'libcurve25519_dalek.so',
    path: 'lib/solace/utils/libcurve25519_dalek-linux/libcurve25519_dalek.so'
  },
  windows: {
    target: 'x86_64-pc-windows-gnu',
    ext: 'dll',
    rustlib: 'curve25519_dalek.dll',
    path: 'lib/solace/utils/libcurve25519_dalek-windows/curve25519_dalek.dll'
  },
  macos: {
    target: 'x86_64-apple-darwin',
    ext: 'dylib',
    rustlib: 'libcurve25519_dalek.dylib',
    path: 'lib/solace/utils/libcurve25519_dalek-macos/libcurve25519_dalek.dylib'
  },
  macos_arm64: {
    target: 'aarch64-apple-darwin',
    ext: 'dylib',
    rustlib: 'libcurve25519_dalek.dylib',
    path: 'lib/solace/utils/libcurve25519_dalek-macos-arm64/libcurve25519_dalek.dylib'
  },
  linux_arm64: {
    target: 'aarch64-unknown-linux-gnu',
    ext: 'so',
    rustlib: 'libcurve25519_dalek.so',
    path: 'lib/solace/utils/libcurve25519_dalek-linux-arm64/libcurve25519_dalek.so'
  }
}.freeze

# Run all Minitest tests
# rake test [test_file]
Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.pattern = ARGV[1] || 'test/**/*_test.rb'
  t.verbose = false
end

# Bootstrap test environment
Rake::TestTask.new(:bootstrap) do |t|
  t.libs << 'test'
  t.pattern = 'test/bootstrap.rb'
  t.verbose = false
end

# Run all usecases
Rake::TestTask.new(:usecases) do |t|
  t.libs << 'test'
  # Get the named usecase from the CLI argument
  t.pattern = "test/usecases/#{ARGV[1] || '*'}.rb"
  t.verbose = false
end

# Compile the Rust library for every supported platform, copying each artifact into
# lib/solace/utils/ where the FFI loader expects it. (build / install / release come
# from bundler/gem_tasks above.)
task :compile do
  PLATFORMS.each do |name, cfg|
    puts "Building for #{name}..."
    sh "cargo build --manifest-path=ext/curve25519_dalek/Cargo.toml --release --target=#{cfg[:target]}"

    src = File.join('ext', 'curve25519_dalek', 'target', cfg[:target], 'release', cfg[:rustlib])
    dest = File.join(cfg[:path])

    FileUtils.mkdir_p(File.dirname(dest))
    FileUtils.cp(src, dest)
  end
end

task default: :test
